language: julia

julia:
  - 1.0
  - nightly

matrix:
  allow_failures:
  - julia: nightly

notifications:
  email: false

os:
  - linux
  - osx
sudo: true
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./test/install_ffmpeg.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ffmpeg; fi
