language: julia
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
  - julia: nightly
notifications:
  email: false
os:
  - linux
  - osx
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - ffmpeg
