name: CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.4]
        julia-arch: [x64]
        os: [ubuntu-latest, macOS-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1.0.0

      - name: Set up Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}

      - name: Add package versions
        run: julia --project=. -e 'using Pkg; pkg"add AbstractPlotting#sd/new_text_layout FreeTypeAbstraction#sd/em-units MakieGallery#master"'

      - name: Run tests
        uses: julia-actions/julia-runtest@master

      - name: Upload recordings
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Recordings
          path: ./test/test_recordings
        if: always()

      - name: Upload diffs
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Recordings
          path: ./test/tested_different
        if: always()

      - name: Upload format tests
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Recordings
          path: ./test/test_formats
        if: always()

      - name: Cache artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
        if: always()
